name: Build Flipper One OS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p out

      - name: Run debos via Official Docker Container
        run: |
          docker run --rm \
            --privileged \
            --device /dev/kvm \
            --workdir /recipes \
            --mount "type=bind,source=$(pwd),destination=/recipes" \
            --security-opt label=disable \
            --entrypoint /bin/bash \
            ghcr.io/go-debos/debos:main \
            -c "./build-ospack.sh"

      - name: Save The Finished File
        uses: actions/upload-artifact@v4
        with:
          name: flipper-one-image
          path: out/
