name: Build Flipper One OS
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # Using the official debos container you found, which already has KVM and tools configured
    container:
      image: ghcr.io/go-debos/debos:main
      options: --device=/dev/kvm --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build The Image
        run: |
          mkdir -p out
          # Because we are inside the official container, debos is already installed natively!
          ./build-ospack.sh

      - name: Save The Finished File
        uses: actions/upload-artifact@v4
        with:
          name: flipper-one-image
          path: out/
